/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.table.DefaultTableModel;
import model.DAO.VendasDAO;
import model.bean.Venda;

/**
 *
 * @author Eduardo
 */
public class ConsumidorF extends javax.swing.JFrame {

    /**
     * Creates new form ConsumidorF
     */
    public ConsumidorF() {
        initComponents();
        
        readJTable();
    }

     public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTConsumidor.getModel();
        modelo.setNumRows(0);
        
        VendasDAO pdao = new VendasDAO();

        for(Venda p: pdao.readConsumidor()){
            
            modelo.addRow(new Object[]{
              p.getClientev(),
              p.getQtd_compras(),
              p.getQtditens(),
              p.getValort()
            });
    
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTConsumidor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTConsumidor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CPF_Cliente", "Qtd_Compras", "Qtd_Produtos", "Valor_Total"
            }
        ));
        jScrollPane1.setViewportView(jTConsumidor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTConsumidor;
    // End of variables declaration//GEN-END:variables
}
