/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Check.ChecarCpf;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DAO.FuncionariosDAO;
import static model.DAO.FuncionariosDAO.List;
import model.bean.Funcionario;

/**
 *
 * @author Eduardo
 */
public class OperacoesFuncionarios extends javax.swing.JFrame {

    /**
     * Creates new form OperacoesFuncionarios
     */
    public OperacoesFuncionarios() {
        initComponents();
        
        readJTable();
    }

     public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTFuncionarios.getModel();
        modelo.setNumRows(0);
        
        FuncionariosDAO pdao = new FuncionariosDAO();

        for(Funcionario f: pdao.read()){
            
            modelo.addRow(new Object[]{
                f.getNome(),
                f.getCpf(),
                f.getEmail(),
                f.getData_nasc(),
                f.getCelular(),
                f.getCep(),
                f.getRua(),
                f.getNumero(),
                f.getFuncao()
            });
    
    }
 }
     public void readJTableFor(String verificar){
        DefaultTableModel modelo = (DefaultTableModel) jTFuncionarios.getModel();
        modelo.setNumRows(0);
        
        FuncionariosDAO pdao = new FuncionariosDAO();

        for(Funcionario f: pdao.readCpf(verificar)){
            
            modelo.addRow(new Object[]{
                f.getNome(),
                f.getCpf(),
                f.getEmail(),
                f.getData_nasc(),
                f.getCelular(),
                f.getCep(),
                f.getRua(),
                f.getNumero(),
                f.getFuncao()
            });
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeFun = new javax.swing.JTextField();
        txtCPFFun = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmailFun = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCelularFun = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCEPFun = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRuaFun = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNumeroFun = new javax.swing.JTextField();
        btnAlterarFun = new javax.swing.JButton();
        btnExcluirFun = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTFuncionarios = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtPesquisarFun = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDataFun = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        choice1 = new java.awt.Choice();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Funcionários");
        setResizable(false);

        jLabel1.setText("Nome");

        jLabel2.setText("CPF");

        try {
            txtCPFFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("Email");

        jLabel4.setText("Celular");

        try {
            txtCelularFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)# ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("CEP");

        try {
            txtCEPFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Rua");

        jLabel7.setText("Número");

        btnAlterarFun.setText("Alterar");
        btnAlterarFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarFunActionPerformed(evt);
            }
        });

        btnExcluirFun.setText("Excluir");
        btnExcluirFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirFunActionPerformed(evt);
            }
        });

        jTFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Email", "Data de Nascimento", "Celular", "CEP", "Rua", "Número", "Função"
            }
        ));
        jTFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTFuncionarios);

        jLabel9.setText("Pesquisar");

        txtPesquisarFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarFunActionPerformed(evt);
            }
        });
        txtPesquisarFun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarFunKeyPressed(evt);
            }
        });

        jLabel8.setText("Data de Nascimento");

        try {
            txtDataFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton1.setText("Atualizar Página");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Função:");

        choice1.add("Supervisor");
        choice1.add("Vendedor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtPesquisarFun, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCelularFun, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCEPFun, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addGap(28, 28, 28))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnAlterarFun, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnExcluirFun)
                                        .addGap(49, 49, 49)
                                        .addComponent(jButton1))
                                    .addComponent(txtRuaFun, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumeroFun, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(0, 32, Short.MAX_VALUE))
                                    .addComponent(choice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNomeFun)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCPFFun, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmailFun, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtDataFun, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))))
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPFFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCelularFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCEPFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRuaFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNumeroFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluirFun)
                    .addComponent(btnAlterarFun)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisarFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarFunActionPerformed

    private void btnAlterarFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarFunActionPerformed
        
         if(jTFuncionarios.getSelectedRow() != -1 && ChecarCpf.checkCpfUsuario(txtCPFFun.getText())){
            
            FuncionariosDAO fdao = new FuncionariosDAO();
            Funcionario f1 = new Funcionario();
            
            f1.setNome(txtNomeFun.getText());
            f1.setCpf((txtCPFFun.getText()));
            f1.setEmail(txtEmailFun.getText());
            f1.setData_nasc(txtDataFun.getText());
            f1.setCelular((txtCelularFun.getText()));
            f1.setCep((txtCEPFun.getText()));
            f1.setRua((txtRuaFun.getText()));
            f1.setNumero((txtNumeroFun.getText()));
            f1.setFuncao(choice1.getSelectedItem());
            
            fdao.update(f1);
            
            txtNomeFun.setText("");
            txtCPFFun.setText("");
            txtEmailFun.setText("");
            txtDataFun.setText("");
            txtCelularFun.setText("");
            txtCEPFun.setText("");
            txtRuaFun.setText("");
            txtNumeroFun.setText("");
            
            
            readJTable();
            
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um registro!");
        }
    }//GEN-LAST:event_btnAlterarFunActionPerformed

    private void btnExcluirFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirFunActionPerformed
        
        if(jTFuncionarios.getSelectedRow() != -1){
            
            FuncionariosDAO fdao = new FuncionariosDAO();
            Funcionario f1 = new Funcionario();
        
        
            f1.setCpf((txtCPFFun.getText()));
            
            fdao.delete(f1);
            
            txtNomeFun.setText("");
            txtCPFFun.setText("");
            txtEmailFun.setText("");
            txtDataFun.setText("");
            txtCelularFun.setText("");
            txtCEPFun.setText("");
            txtRuaFun.setText("");
            txtNumeroFun.setText("");
            
            readJTable();
     
        
        }
    }//GEN-LAST:event_btnExcluirFunActionPerformed

    private void jTFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFuncionariosMouseClicked
        
        if (jTFuncionarios.getSelectedRow() != -1){
            
           txtNomeFun.setText(jTFuncionarios.getValueAt(jTFuncionarios.getSelectedRow(), 0).toString());
           txtCPFFun.setText(jTFuncionarios.getValueAt(jTFuncionarios.getSelectedRow(), 1).toString());
           txtEmailFun.setText(jTFuncionarios.getValueAt(jTFuncionarios.getSelectedRow(), 2).toString());
           txtDataFun.setText(jTFuncionarios.getValueAt(jTFuncionarios.getSelectedRow(), 3).toString());
           txtCelularFun.setText(jTFuncionarios.getValueAt(jTFuncionarios.getSelectedRow(), 4).toString());
           txtCEPFun.setText(jTFuncionarios.getValueAt(jTFuncionarios.getSelectedRow(), 5).toString());
           txtRuaFun.setText(jTFuncionarios.getValueAt(jTFuncionarios.getSelectedRow(), 6).toString());
           txtNumeroFun.setText(jTFuncionarios.getValueAt(jTFuncionarios.getSelectedRow(), 7).toString());
          
        }
    }//GEN-LAST:event_jTFuncionariosMouseClicked

    private void txtPesquisarFunKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarFunKeyPressed
        // TODO add your handling code here:
        
        ArrayList <Funcionario> prod = List(txtPesquisarFun.getText());
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new Object[]{"Nome","CPF","Email","Nascimento","Celular","CEP","Rua","Número","Função"});
            Object[] row = new Object [9] ;
            for(int i=0;i < prod.size(); i++)
            {
                row[0] = prod.get(i).getNome();
                row[1] = prod.get(i).getCpf();
                row[2] = prod.get(i).getEmail();
                row[3] = prod.get(i).getData_nasc();
                row[4] = prod.get(i).getCelular();
                row[5] = prod.get(i).getCep(); 
                row[6] = prod.get(i).getRua();
                row[7] = prod.get(i).getNumero();
                row[8] = prod.get(i).getFuncao();
                /*txtNomeFun.setText((String) row[0]);
                txtCPFFun.setText((String) row[1]);
                txtEmailFun.setText((String) row[2]);
                txtDataFun.setText((String) row[3]);
                txtCelularFun.setText((String) row[4]);
                txtCEPFun.setText((String) row[5]);
                txtRuaFun.setText((String) row[6]);
                txtNumeroFun.setText((String) row[7]);*/
                model.addRow(row);
            }   
                  jTFuncionarios.setModel(model);   
    }//GEN-LAST:event_txtPesquisarFunKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            txtNomeFun.setText("");
            txtCPFFun.setText("");
            txtEmailFun.setText("");
            txtDataFun.setText("");
            txtCelularFun.setText("");
            txtCEPFun.setText("");
            txtRuaFun.setText("");
            txtNumeroFun.setText("");
            txtPesquisarFun.setText("");
            
            readJTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarFun;
    private javax.swing.JButton btnExcluirFun;
    private java.awt.Choice choice1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTFuncionarios;
    private javax.swing.JFormattedTextField txtCEPFun;
    private javax.swing.JFormattedTextField txtCPFFun;
    private javax.swing.JFormattedTextField txtCelularFun;
    private javax.swing.JFormattedTextField txtDataFun;
    private javax.swing.JTextField txtEmailFun;
    private javax.swing.JTextField txtNomeFun;
    private javax.swing.JTextField txtNumeroFun;
    private javax.swing.JTextField txtPesquisarFun;
    private javax.swing.JTextField txtRuaFun;
    // End of variables declaration//GEN-END:variables
}
