/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Check.ChecarCpf;
import javax.swing.JOptionPane;
import model.DAO.VendasDAO;
import model.DAO.VendasProdutosDAO;
import model.bean.Venda;

/**
 *
 * @author isac_
 */
public class Receber extends javax.swing.JFrame {

    /**
     * Creates new form Receber
     */
    public Receber() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtValorr = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLtroco = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("CPF do cliente:");

        jLabel4.setText("Valor recebido:");

        txtValorr.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtValorr.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtValorrMouseMoved(evt);
            }
        });
        txtValorr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorrKeyPressed(evt);
            }
        });

        jButton1.setText("Finalizar");
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLtroco.setText("00,00");

        jLabel5.setText("Troco:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValorr, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLtroco, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtValorr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLtroco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addGap(32, 32, 32))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String a1 = txtValorr.getText();
        String a1c = a1.replaceAll(",", ".");
        double v1 = Double.parseDouble(a1c);
        double vt = VendasProdutosDAO.getValorTotalProductID();
        if(ChecarCpf.checkCpfCliente(txtCpf.getText()) && v1 >= vt) { // debugar
            // possivel problema no txtValorr
            Venda v = new Venda();
            VendasDAO vdao = new VendasDAO();
            
            v.setClientev(txtCpf.getText());
            v.setIdvenda(VendasProdutosDAO.getAutoIncrementProductID());
            vdao.update2(v);  
            
            JOptionPane.showMessageDialog(null, "Venda finalizada com sucesso!");
            this.dispose();
            
        } else {
            JOptionPane.showMessageDialog(null, "CPF inválido ou Valor recebido abaixo do esperado.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtValorrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorrKeyPressed
        // TODO add your handling code here:
        
        String a1 = txtValorr.getText();
        String a1c = a1.replaceAll(",", ".");
        double v1 = Double.parseDouble(a1c);
        double vt = VendasProdutosDAO.getValorTotalProductID();
        double troco = v1 - vt;
        jLtroco.setText("R$"+String.valueOf(troco)+"0");
        
    }//GEN-LAST:event_txtValorrKeyPressed

    private void txtValorrMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtValorrMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorrMouseMoved

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        // TODO add your handling code here:
        /*String a1 = txtValorr.getText();
        String a1c = a1.replaceAll(",", ".");
        double v1 = Double.parseDouble(a1c);
        double vt = VendasProdutosDAO.getValorTotalProductID();
        double troco = v1 - vt;
        jLtroco.setText("R$"+String.valueOf(troco)+"0");  */      
    }//GEN-LAST:event_jButton1MouseMoved

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLtroco;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtValorr;
    // End of variables declaration//GEN-END:variables
}
