/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewA;

import Check.ChecarCNPJ;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DAO.ProdutoDAO;
import static model.DAO.ProdutoDAO.List;
import model.bean.Produto;

/**
 *
 * @author Eduardo
 */
public class OperacoesProdutosA extends javax.swing.JFrame {

    /**
     * Creates new form OperacoesProdutos
     */
    public OperacoesProdutosA() {
        initComponents();
        
        readJTable();
    }

    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTProdutos.getModel();
        modelo.setNumRows(0);
        
        ProdutoDAO pdao = new ProdutoDAO();

        for(Produto p: pdao.read()){
            
            modelo.addRow(new Object[]{
                p.getCodigo(),
                p.getNome(),
                p.getPreco(),
                p.getQtd(),
                p.getDescricao(),
                p.getData_fabri(),
                p.getCnpj_fornec()
            });
    
    }
 }
     public void readJTableFor(String verificar){
        
        DefaultTableModel modelo = (DefaultTableModel) jTProdutos.getModel();
        modelo.setNumRows(0);
        
        ProdutoDAO pdao = new ProdutoDAO();

        for(Produto p: pdao.readCodigo(verificar)){
            
            modelo.addRow(new Object[]{
                p.getCodigo(),
                p.getNome(),
                p.getPreco(),
                p.getQtd(),
                p.getDescricao(),
                p.getData_fabri(),
                p.getCnpj_fornec()
            });
    
    }
        
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrecoP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDescP = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProdutos = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtPesquisarP = new javax.swing.JTextField();
        txtQtdP = new javax.swing.JTextField();
        btnRegistrarP = new javax.swing.JButton();
        txtDataP = new javax.swing.JFormattedTextField();
        txtCodFP = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCodigoP = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos");

        jLabel1.setText("Nome");

        jLabel2.setText("Quantidade");

        jLabel3.setText("Preço");

        jLabel4.setText("Descrição");

        jLabel5.setText("CNPJ do Fornecedor");

        jLabel6.setText("Data de Fabricação");

        jTProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Preço", "Quantidade", "Descrição", "Data de Fabricação", "CNPJ do Fornecedor"
            }
        ));
        jTProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTProdutos);

        jLabel9.setText("Pesquisar");

        txtPesquisarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarPActionPerformed(evt);
            }
        });
        txtPesquisarP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarPKeyPressed(evt);
            }
        });

        btnRegistrarP.setText("Registrar");
        btnRegistrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPActionPerformed(evt);
            }
        });

        try {
            txtDataP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCodFP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setText("Código");

        jButton1.setText("Atualizar Página");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtPrecoP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtQtdP, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigoP)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtPesquisarP, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(txtDescP, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDataP, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addComponent(jButton1))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(txtCodFP, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(btnRegistrarP)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQtdP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodFP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarP)
                    .addComponent(jButton1))
                .addGap(31, 31, 31)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtCodigoP.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarPActionPerformed

    private void btnRegistrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPActionPerformed
        
        
        if(ChecarCNPJ.checkCnpj(txtCodFP.getText())){
            
        ProdutoDAO fdao = new ProdutoDAO();
        Produto p1 = new Produto();
        
        p1.setNome(txtNomeP.getText());
        p1.setPreco(Double.parseDouble(txtPrecoP.getText()));
        p1.setQtd(Integer.parseInt(txtQtdP.getText()));
        p1.setDescricao((txtDescP.getText()));
        p1.setData_fabri((txtDataP.getText()));
        p1.setCnpj_fornec((txtCodFP.getText()));
       
        
        fdao.create(p1);
            
        txtNomeP.setText("");
        txtPrecoP.setText("");
        txtQtdP.setText("");
        txtDescP.setText("");
        txtDataP.setText("");
        txtCodFP.setText("");
        
        readJTable();
        }else{
            JOptionPane.showMessageDialog(null, " O CNPJ não está registrado");
        }
    }//GEN-LAST:event_btnRegistrarPActionPerformed

    private void jTProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTProdutosMouseClicked
        
        if (jTProdutos.getSelectedRow() != -1){
            
           txtCodigoP.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 0).toString());
           txtNomeP.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 1).toString());
           txtPrecoP.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 2).toString());
           txtQtdP.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 3).toString());
           txtDescP.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 4).toString());
           txtDataP.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 5).toString());
           txtCodFP.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 6).toString());
          
                    
        }
    }//GEN-LAST:event_jTProdutosMouseClicked

    private void txtPesquisarPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarPKeyPressed
        // TODO add your handling code here:
        
        ArrayList <Produto> prod = List(txtPesquisarP.getText());
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new Object[]{"Código","Nome","Preço","Quantidade","Descricao","Fabricação","Fornecedor"});
            Object[] row = new Object [7] ;
            for(int i=0;i < prod.size(); i++)
            {
                row[0] = prod.get(i).getCodigo();
                row[1] = prod.get(i).getNome();
                row[2] = prod.get(i).getPreco();
                row[3] = prod.get(i).getQtd();
                row[4] = prod.get(i).getDescricao();
                row[5] = prod.get(i).getData_fabri(); 
                row[6] = prod.get(i).getCnpj_fornec();
                
                int cod = prod.get(i).getCodigo();
                String cods = String.valueOf(cod);
                txtCodigoP.setText(cods);
                txtNomeP.setText((String) row[1]);
                Double price = prod.get(i).getPreco();
                String prices = Double.toString(price);
                txtPrecoP.setText(prices);
                int qtd = prod.get(i).getQtd();
                String qtds = String.valueOf(qtd);
                txtQtdP.setText(qtds);
                txtDescP.setText((String) row[4]);
                txtDataP.setText((String) row[5]);
                txtCodFP.setText((String) row[6]);
                
                model.addRow(row);
            }   
                  jTProdutos.setModel(model);
        
    }//GEN-LAST:event_txtPesquisarPKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            txtNomeP.setText("");
            txtPrecoP.setText("");
            txtQtdP.setText("");
            txtDescP.setText("");
            txtDataP.setText("");
            txtCodFP.setText("");
            txtPesquisarP.setText("");
            
            
            readJTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarP;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTProdutos;
    private javax.swing.JFormattedTextField txtCodFP;
    private javax.swing.JTextField txtCodigoP;
    private javax.swing.JFormattedTextField txtDataP;
    private javax.swing.JTextField txtDescP;
    private javax.swing.JTextField txtNomeP;
    private javax.swing.JTextField txtPesquisarP;
    private javax.swing.JTextField txtPrecoP;
    private javax.swing.JTextField txtQtdP;
    // End of variables declaration//GEN-END:variables
}
