/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewA;

import Check.ChecarCNPJ;
import Check.ValidarEmail;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DAO.FornecedoresDAO;
import static model.DAO.FornecedoresDAO.List;
import model.bean.Fornecedor;

/**
 *
 * @author Eduardo
 */
public class OperacoesFornecedoresA extends javax.swing.JFrame {

    /**
     * Creates new form OperacoesFornecedores
     */
    public OperacoesFornecedoresA() {
        initComponents();
        
        readJTable();
    }
    
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTFornecedor.getModel();
        modelo.setNumRows(0);
        
        FornecedoresDAO pdao = new FornecedoresDAO();

        for(Fornecedor f: pdao.read()){
            
            modelo.addRow(new Object[]{
                f.getNome(),
                f.getCnpj(),
                f.getEmail(),
                f.getCelular(),
                f.getCep(),
                f.getRua(),
                f.getNumero()
            });
    
    }
 }
     public void readJTableFor(String verificar){
        DefaultTableModel modelo = (DefaultTableModel) jTFornecedor.getModel();
        modelo.setNumRows(0);
        
        FornecedoresDAO pdao = new FornecedoresDAO();

        for(Fornecedor f: pdao.readCnpj(verificar)){
            
            modelo.addRow(new Object[]{
                f.getNome(),
                f.getCnpj(),
                f.getEmail(),
                f.getCelular(),
                f.getCep(),
                f.getRua(),
                f.getNumero()
            });
        }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeFor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmailFor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCelularFor = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCEPFor = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRuaFor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNumeroFor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTFornecedor = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtPesquisarFor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCNPJFor = new javax.swing.JFormattedTextField();
        btnRegistrarFor = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fornecedores");
        setResizable(false);

        jLabel1.setText("Nome");

        jLabel3.setText("Email");

        jLabel4.setText("Celular");

        try {
            txtCelularFor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)# ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("CEP");

        try {
            txtCEPFor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Rua");

        jLabel7.setText("Número");

        jTFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "CNPJ", "Email", "Telefone", "CEP", "Rua", "Número"
            }
        ));
        jTFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFornecedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTFornecedor);

        jLabel9.setText("Pesquisar");

        txtPesquisarFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarForActionPerformed(evt);
            }
        });
        txtPesquisarFor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarForKeyPressed(evt);
            }
        });

        jLabel2.setText("CNPJ");

        try {
            txtCNPJFor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCNPJFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNPJForActionPerformed(evt);
            }
        });

        btnRegistrarFor.setText("Registrar");
        btnRegistrarFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarForActionPerformed(evt);
            }
        });

        jButton1.setText("Atualizar Página");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeFor, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCNPJFor, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtEmailFor, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtPesquisarFor, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(txtCelularFor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCEPFor, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtRuaFor, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeroFor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btnRegistrarFor)
                        .addGap(95, 95, 95)
                        .addComponent(jButton1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCNPJFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCelularFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCEPFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRuaFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarFor)
                    .addComponent(jButton1))
                .addGap(11, 11, 11)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtPesquisarFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarForActionPerformed

    private void txtCNPJForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNPJForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNPJForActionPerformed

    private void btnRegistrarForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarForActionPerformed
    
     FornecedoresDAO fdao = new FornecedoresDAO();
        Fornecedor f1 = new Fornecedor();
        
        if (!ChecarCNPJ.checkCnpj(txtCNPJFor.getText()) && ValidarEmail.Valido(txtEmailFor.getText())) {
        
        f1.setNome(txtNomeFor.getText());
        f1.setCnpj((txtCNPJFor.getText()));
        f1.setEmail(txtEmailFor.getText());
        f1.setCelular((txtCelularFor.getText()));
        f1.setCep((txtCEPFor.getText()));
        f1.setRua((txtRuaFor.getText()));
        f1.setNumero((txtNumeroFor.getText()));
        
        fdao.create(f1);
            
        txtNomeFor.setText("");
        txtCNPJFor.setText("");
        txtEmailFor.setText("");
        txtCelularFor.setText("");
        txtCEPFor.setText("");
        txtRuaFor.setText("");
        txtNumeroFor.setText("");
        
        readJTable();
        
        } else {
          JOptionPane.showMessageDialog(null, "CNPJ já existe ou o email está inválido!");  
        }
        
    }//GEN-LAST:event_btnRegistrarForActionPerformed

    private void jTFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFornecedorMouseClicked
        
        if (jTFornecedor.getSelectedRow() != -1){
            
           txtNomeFor.setText(jTFornecedor.getValueAt(jTFornecedor.getSelectedRow(), 0).toString());
           txtCNPJFor.setText(jTFornecedor.getValueAt(jTFornecedor.getSelectedRow(), 1).toString());
           txtEmailFor.setText(jTFornecedor.getValueAt(jTFornecedor.getSelectedRow(), 2).toString());
           txtCelularFor.setText(jTFornecedor.getValueAt(jTFornecedor.getSelectedRow(), 3).toString());
           txtCEPFor.setText(jTFornecedor.getValueAt(jTFornecedor.getSelectedRow(), 4).toString());
           txtRuaFor.setText(jTFornecedor.getValueAt(jTFornecedor.getSelectedRow(), 5).toString());
           txtNumeroFor.setText(jTFornecedor.getValueAt(jTFornecedor.getSelectedRow(), 6).toString());
           
        }
    }//GEN-LAST:event_jTFornecedorMouseClicked

    private void txtPesquisarForKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarForKeyPressed
        // TODO add your handling code here:
        
        ArrayList<Fornecedor> prod = List(txtPesquisarFor.getText());
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new Object[]{"Nome","CNPJ","Email","Telefone","CEP","Rua","Número"});
            Object[] row = new Object [7] ;
            for(int i=0;i < prod.size(); i++)
            {
                row[0] = prod.get(i).getNome();
                row[1] = prod.get(i).getCnpj();
                row[2] = prod.get(i).getEmail();
                row[3] = prod.get(i).getCelular();
                row[4] = prod.get(i).getCep(); 
                row[5] = prod.get(i).getRua();
                row[6] = prod.get(i).getNumero();
                txtNomeFor.setText((String) row[0]);
                txtCNPJFor.setText((String) row[1]);
                txtCelularFor.setText((String) row[3]);
                txtEmailFor.setText((String) row[2]);
                txtCEPFor.setText((String) row[4]);
                txtRuaFor.setText((String) row[5]);
                txtNumeroFor.setText((String) row[6]);
                model.addRow(row);
            }   
                  jTFornecedor.setModel(model);
        
    }//GEN-LAST:event_txtPesquisarForKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            txtNomeFor.setText("");
            txtCNPJFor.setText("");
            txtEmailFor.setText("");
            txtCelularFor.setText("");
            txtCEPFor.setText("");
            txtRuaFor.setText("");
            txtNumeroFor.setText("");
            txtPesquisarFor.setText("");
            
            readJTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarFor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTFornecedor;
    private javax.swing.JFormattedTextField txtCEPFor;
    private javax.swing.JFormattedTextField txtCNPJFor;
    private javax.swing.JFormattedTextField txtCelularFor;
    private javax.swing.JTextField txtEmailFor;
    private javax.swing.JTextField txtNomeFor;
    private javax.swing.JTextField txtNumeroFor;
    private javax.swing.JTextField txtPesquisarFor;
    private javax.swing.JTextField txtRuaFor;
    // End of variables declaration//GEN-END:variables
}
